package com.example.workshift.business.exception;

import lombok.Getter;

@Getter
public enum ErrorType {
    SHIFT_DURATION_INVALID("SHIFT_DURATION_INVALID"),
    SHIFT_DURATION_MORE_THAN_EIGHT_HOURS("SHIFT_DURATION_MORE_THAN_EIGHT_HOURS"),
    SHIFT_CREATION_IN_THE_PAST("SHIFT_CREATION_IN_THE_PAST"),
    MAX_HOURS_IN_THE_SAME_SHOP_WITHIN_24_HOUR_WINDOW_EXCEEDED("MAX_HOURS_IN_THE_SAME_SHOP_WITHIN_24_HOUR_WINDOW_EXCEEDED"),
    MORE_THAN_FIVE_DAYS_IN_A_ROW_IN_THE_SAME_SHOP("MORE_THAN_FIVE_DAYS_IN_A_ROW_IN_THE_SAME_SHOP"),
    ACTIVE_SHIFT_EXISTS("ACTIVE_SHIFT_EXISTS"),
    USER_NOT_FOUND("USER_NOT_FOUND"),
    SHOP_NOT_FOUND("SHOP_NOT_FOUND"),
    SERVER_ERROR("SERVER_ERROR");

    private final String errorCode;

    ErrorType(String errorCode) {
        this.errorCode = errorCode;
    }
}
